version: '3.9'

services:
  drawchat:
    build:
      dockerfile: ./os/ubuntu/Dockerfile
      context: .
    image: drawchat
    container_name: drawchat
    volumes:
      - ..:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/.git
      - /var/www/html/node_modules
      - /var/www/html/bootstrap/cache
    ports:
      - '80:80'
      - '443:443'
    privileged: true

## for db permanent
#volumes:
#    db_data:
